# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccset',
            options={'verbose_name': 'CoachingCentre', 'verbose_name_plural': 'CoachingCentres'},
        ),
        migrations.AlterModelOptions(
            name='clset',
            options={'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='ptset',
            options={'verbose_name': 'PrivateTuition', 'verbose_name_plural': 'PrivateTuitions'},
        ),
        migrations.AlterModelOptions(
            name='shset',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AddField(
            model_name='ccset',
            name='source_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.SourceSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clset',
            name='source_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.SourceSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptset',
            name='source_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.SourceSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shset',
            name='source_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.SourceSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shset',
            name='seats_left',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='contact_num',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='ehub_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='contact_num',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
