# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170723_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userset',
            name='uuid',
        ),
    ]
