# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170725_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formstatusset',
            old_name='form_type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='h9pjipi7-1500927214491-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='izi9n8ei-1500927214491-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='uuso91jf-1500927214491-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='dgbba5os-1500927214491-SH', editable=False, max_length=40, unique=True),
        ),
    ]
