# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170725_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='v04pycxg-1500959521678-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='zlgcoh1d-1500959521663-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='oi7jcww1-1500959521663-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='539cg7p8-1500959521663-SH', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ccset',
            unique_together=set([('source_id', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='clset',
            unique_together=set([('source_id', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='ptset',
            unique_together=set([('source_id', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='shset',
            unique_together=set([('source_id', 'till_class')]),
        ),
    ]
