# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170725_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='9cnq7nyd-1501254301142-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='nwnqzvpa-1501254301139-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='16244s61-1501254301134-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='773jyfa4-1501254301136-SH', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
