# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170731_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='4dn4fp1r-1501568271438-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='x8sgi4bj-1501568271438-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='akdfuk6q-1501568271423-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='tybicrbw-1501568271423-SH', editable=False, max_length=40, unique=True),
        ),
    ]
