# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170902_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='8jujq8fv-1504374465344-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='ky2c6qg7-1504374465344-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='wmqbuv1l-1504374465344-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='rid5w78e-1504374465344-SH', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sourceset',
            unique_together=set([('email', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='userset',
            unique_together=set([('email', 'name')]),
        ),
    ]
