# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170902_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='0ibx8wiv-1504374509056-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='5798pb2k-1504374509052-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='7u9fxrcu-1504374509048-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='t2o80xv8-1504374509048-SH', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sourceset',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
