# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0023_auto_20170902_2318'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userset',
            managers=[
                ('objects', main.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userset',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userset',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userset',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userset',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='0kh53hg5-1504941710572-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='s45k63x4-1504941710571-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='formstatusset',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('W', 'Waiting'), ('C', 'Cancelled')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='4bwhp0xi-1504941710569-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='cg5ztmg1-1504941710570-SH', editable=False, max_length=40, unique=True),
        ),
    ]
