# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170909_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(default='9lj3w2uz-1504943636976-CC', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(default='593m57wm-1504943636973-CL', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(default='xwkga000-1504943636967-PT', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(default='d8g121xn-1504943636970-SH', editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
