# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170909_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccset',
            name='uuid',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clset',
            name='uuid',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ptset',
            name='uuid',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shset',
            name='uuid',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
