# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170915_1057'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userset',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userset',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userset',
            name='user_permissions',
        ),
    ]
